### ISSUE TITLE
Failed to download SpatialOS Core Sdk version 13.7.1-gdk-for-unity

### ISSUE THREAD

**Issue by Saucy** [spatialos/gdk-for-unity#1008]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).

-------

#### Description
Failing to install Core SDK version 13.7.1-gdk-for-unity. When I open the FPS starter project or the Blank project it fails to download and install Core SDK version 13.7.1-gdk-for-unity.

## Expected behaviour
Download and install the SDK during/after opening the projects.

## Current behaviour
I open the project to set it up but it fails downloading SDK.

## Possible solution
-

## Steps to reproduce
1. Follow the steps on the official docs: https://docs.improbable.io/unity/alpha/projects/fps/get-started/set-up for Windows 10 64bit
2. Clone the projects using SSH
3. Both folders are under same parent
4. Opening the project fails to download the SDK

## Environment
Install and setup the blank project available on GitHub.

`Downloading core-dynamic-x86-win32 to H:\dev\game\Unity\gdk-for-unity-blank-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86-win32.zip...

  Successfully retrieved package type 'worker_sdk' with name 'core-dynamic-x86-win32' and version '13.7.1-gdk-for-unity' to 'H:\dev\game\Unity\gdk-for-unity-blank-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86-win32.zip'

  Downloading core-dynamic-x86_64-win32 to H:\dev\game\Unity\gdk-for-unity-blank-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86_64-win32.zip...

  Successfully retrieved package type 'worker_sdk' with name 'core-dynamic-x86_64-win32' and version '13.7.1-gdk-for-unity' to 'H:\dev\game\Unity\gdk-for-unity-blank-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86_64-win32.zip'

  Downloading core-dynamic-x86_64-linux to H:\dev\game\Unity\gdk-for-unity-blank-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86_64-linux.zip...

  Successfully retrieved package type 'worker_sdk' with name 'core-dynamic-x86_64-linux' and version '13.7.1-gdk-for-unity' to 'H:\dev\game\Unity\gdk-for-unity-blank-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86_64-linux.zip'

  Downloading core-bundle-x86_64-macos to H:\dev\game\Unity\gdk-for-unity-blank-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-bundle-x86_64-macos.zip...

  Successfully retrieved package type 'worker_sdk' with name 'core-bundle-x86_64-macos' and version '13.7.1-gdk-for-unity' to 'H:\dev\game\Unity\gdk-for-unity-blank-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-bundle-x86_64-macos.zip'

  Downloading core-static-fullylinked-arm-ios to H:\dev\game\Unity\gdk-for-unity-blank-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-static-fullylinked-arm-ios.zip...

  Downloading...

  Encountered an error during command execution.

  System.Exception: Exit code 1 while running:

  H:\dev\programs\.improbable\spatial\spatial.exe

    --json_output

    package

    retrieve

    worker_sdk

    core-static-fullylinked-arm-ios

    13.7.1-gdk-for-unity

    "H:\dev\game\Unity\gdk-for-unity-blank-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-static-fullylinked-arm-ios.zip"

    at Improbable.Common.RunRedirected(String command, String[] arguments) in H:\dev\game\Unity\gdk-for-unity\workers\unity\Packages\com.improbable.gdk.tools\.DownloadCoreSdk\Common.cs:line 92

    at Improbable.Program.DownloadPackages(IEnumerable`1 packages, String spatialPath, String coreSdkVersion) in H:\dev\game\Unity\gdk-for-unity\workers\unity\Packages\com.improbable.gdk.tools\.DownloadCoreSdk\Program.cs:line 98

    at Improbable.Program.Main(String[] args) in H:\dev\game\Unity\gdk-for-unity\workers\unity\Packages\com.improbable.gdk.tools\.DownloadCoreSdk\Program.cs:line 55

  UnityEngine.Debug:LogError(Object)
  Improbable.Gdk.Tools.RedirectedProcess:Run() (at H:/dev/game/Unity/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs:156)
  Improbable.Gdk.Tools.DownloadCoreSdk:Download() (at H:/dev/game/Unity/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs:133)
  Improbable.Gdk.Tools.DownloadCoreSdk:TryDownload() (at H:/dev/game/Unity/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs:111)
  Improbable.Gdk.Tools.GenerateCode:Generate() (at H:/dev/game/Unity/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs:76)
  Improbable.Gdk.Tools.GenerateCode:InitializeOnLoad() (at H:/dev/game/Unity/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs:49)
`

`Failed to download SpatialOS Core Sdk version 13.7.1-gdk-for-unity. You can use SpatialOS -> Download CoreSDK (force) to retry this.
UnityEngine.Debug:LogError(Object)
Improbable.Gdk.Tools.DownloadCoreSdk:Download() (at H:/dev/game/Unity/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs:139)
Improbable.Gdk.Tools.DownloadCoreSdk:TryDownload() (at H:/dev/game/Unity/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs:111)
Improbable.Gdk.Tools.GenerateCode:Generate() (at H:/dev/game/Unity/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs:76)
Improbable.Gdk.Tools.GenerateCode:InitializeOnLoad() (at H:/dev/game/Unity/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs:49)`

Windows 10 64bit, Unity 2019.1.3f1 (as installation guide say)

**Comment by jamiebrynes7** [comment]
Hey @Saucy, thanks for the report. This error is due to the package download timing out. `core-static-fullylinked-arm-ios.zip` is a particularly large package. 

Some of the work we are doing for publishing the GDK as NPM packages (#894) should solve this problem as the packages will be downloaded from a different service. This is planned to be released in `v0.2.5`.

In the meantime, I'll pass on the report to the team which owns the `spatial` tool to see if we can solve the underlying problem.

**Comment by Saucy** [comment]
Thanks for the update. It could time out because my internet isn't the best. I'll give it another try once v0.2.5 is out!
