### ISSUE TITLE
MonoBehaviours with a WorkerType annotation, but no requirables, do not get enabled

### ISSUE THREAD

**Issue by paulbalaji** [spatialos/gdk-for-unity#1084]
**Affects:** Release v0.2.0 and up
**Internal Ticket:** [UTY-2163](https://improbableio.atlassian.net/browse/UTY-2163)

---

#### Description

A MonoBehaviour with a `WorkerType` attribute will not be enabled if there are no requirables in the script.

For example, the following will not be enabled on a client, even though it has the client WorkerType and does not depend on any requirables to be satisfied.

```csharp
using Improbable.Gdk.Subscriptions;
using UnityEngine;

namespace Scripts.Sphere
{
    [WorkerType("UnityClient")]
    public class ObjectColorBehaviour : MonoBehaviour
    {
        private void Update()
        {
            Debug.Log("Test");
        }
    }
}
```

#### Workaround

There are two potential workarounds for this issue.

1 - Ensure there is a requirable that is valid for the given `WorkerType`.
2 - Define your prefabs based on the `WorkerType`.

**Comment by zeroZshadow** [comment]
Fixed in 0.2.9
