### ISSUE TITLE
Local launch errors on MacOS when project path contains spaces

### ISSUE THREAD

**Issue by paulbalaji** [spatialos/gdk-for-unity#1225]
**Affects:** Release v0.1.0 and up
**Internal Ticket:** [UTY-2380](https://improbableio.atlassian.net/browse/UTY-2380)

---

#### Description

If your spatial project path contains spaces, attempting a local launch will result in errors in the Unity Editor like below:
```
Errors occured - For more information, check the spatial local launch logfile: /Users/username/project path with spaces/logs/spatial_20191125T162432.log
UnityEngine.Debug:LogError(Object)
Improbable.Gdk.Tools.<>c__DisplayClass13_0:<LaunchLocalDeployment>b__0(Object, EventArgs) (at Library/PackageCache/io.improbable.gdk.tools@0.3.0/LocalLaunch.cs:280)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()
```

#### Workaround

Remove all spaces from your project path.

**Comment by jamiebrynes7** [comment]
Released a fix in [0.3.10](https://github.com/spatialos/gdk-for-unity/releases/tag/0.3.10)
