### ISSUE TITLE
Builds which aren't required and the user does not have build support for are not skipped

### ISSUE THREAD

**Issue by jamiebrynes7** [spatialos/gdk-for-unity#1258]
**Affects:** Release v0.3.2 and up
**Internal Ticket:** [UTY-2415](https://improbableio.atlassian.net/browse/UTY-2415)

---

#### Description

If your [build configuration](https://docs.improbable.io/unity/alpha/modules/build-system/build-config) specifies a build target which is `Build`, but not `Required` and a user doesn't have the required build support installed the build is not skipped, even though the console log indicates that it should.

#### Workaround

Temporarily untick the offending build target _or_ install the underlying build support.

**Comment by jamiebrynes7** [comment]
A fix was merged in #1257 and will be released in v0.3.3

**Comment by paulbalaji** [comment]
This has now been released: https://github.com/spatialos/gdk-for-unity/releases/tag/0.3.3
