### ISSUE TITLE
Schema compiler errors are swallowed by the code generator

### ISSUE THREAD

**Issue by jamiebrynes7** [spatialos/gdk-for-unity#1259]
**Affects:** Release v0.3.2 and up
**Internal Ticket:** [UTY-2423](https://improbableio.atlassian.net/browse/UTY-2423)

---

#### Description

If the schema compiler fails to run, the code generator swallows the error instead of forwarding it to the Unity console.

#### Workaround

Open the code generator log and run the same command that "failed to run" to view the errors.

**Comment by jamiebrynes7** [comment]
A fix was merged in #1266 and will be fixed in v0.3.3

**Comment by paulbalaji** [comment]
This has now been released: https://github.com/spatialos/gdk-for-unity/releases/tag/0.3.3
