### ISSUE TITLE
Windows Unable to use Local Launch

### ISSUE THREAD

**Issue by tjones0808** [spatialos/gdk-for-unity#1309]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).

-------

#### Description
Describe your issue.
Whenever I run the the local launch its immediately closes the terminal and i cant go to the inspector.

Logs
>  info SpatialOS starting. [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug starting fabric node master [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug Will invoke java binary at C:\Users\King\AppData\Local\Temp\improbable_extracted_packages\87f6ffea625d605fb00b9f17d59d350f/bin/java.exe [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug Registered fabric nanny dns entries [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug master node elected with ip(127.0.0.1) current node ip(127.0.0.1) [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug fetched java params from etcd [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug fabric classpath size: 1 [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug Starting fabric with args [C:\Users\King\AppData\Local\Temp\improbable_extracted_packages\87f6ffea625d605fb00b9f17d59d350f/bin/java.exe -XX:+PreserveFramePointer -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=25 -XX:G1MaxNewSizePercent=75 -XX:MaxGCPauseMillis=10 -Xmx13355M -Xms2225M -DFABRIC_LOG_LEVEL=WARN -DNET_IMPROBABLE_ASSETS_DIR=C:\Projects\gdk-for-unity-blank-project\build\assembly -DSERVICE_ACCOUNT_REFRESH_TOKEN=some_refresh_token -Dlogback.configurationFile=/improbable/logs/log_config.xml -DAPPDATA=/improbable/logs/fsim -DPROPERTY_EXTERNAL_IP=127.0.0.1 -DPROPERTY_INTERNAL_IP=127.0.0.1 -DPROPERTY_ASSET_DATABASE_URL=http://127.0.0.1:1238 -DLOGSINK_ADDRESS=http://localhost:22000 -DMANAGED_WORKER_LOGFILE_DIRECTORY=C:\Projects\gdk-for-unity-blank-project\logs\2020-03-01_02-11-01\workers -DFABRIC_LOG_DIRECTORY=C:\Projects\gdk-for-unity-blank-project\logs\2020-03-01_02-11-01 -classpath C:\Users\King\AppData\Local\Temp\fabric_bundles\14.4.0/runtime_deploy.jar improbable.deployment.GameLauncher --controller_grpc_port=22000 --fabric_public_ip=127.0.0.1 --deployment_node=master --deployment_project=unity_gdk --node_name=master --deployment_assembly_name=local_assembly --controller_grpc_host=127.0.0.1 --auth_server_base_url=http://127.0.0.1:21000 --deployment_name=local --thor_grpc_tls_host=127.0.0.1 --thor_grpc_tls_port=22000 --thor_grpc_use_tls=false] [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug JVM process id: 6676 [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug JVM did not exit cleanly [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug Cleaning up local services [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug Cleaning up local worker nanny service. [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
info SpatialOS terminated. [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]
debug wrapper services endpoint shut down gracefully [cli-version: 20191125.203150.3993fbd64a] [timestamp: 2020-03-01T02:11:02-05:00]

## Steps to reproduce

1. Download Blank Project
2. Run Powershell setup script
3. Open in Unity
4. Run Local

**Comment by zeroZshadow** [comment]
Could you include the `runtime.log` file found in `C:\Projects\gdk-for-unity-blank-project\logs\2020-03-01_02-11-01` ? This has more detailed information about the local deployment.

**Comment by tjones0808** [comment]
that folder is empty for some reason

**Comment by zeroZshadow** [comment]
Are you still having this issue?

**Comment by tjones0808** [comment]
i was able to get it working, thanks!
