### ISSUE TITLE
Feature Request: EntityCreation

### ISSUE THREAD

**Issue by No3371** [spatialos/gdk-for-unity#1397]
#### Description
Working in ECS workflow, it seems we can only query for `NewlyAddedSpatialOSEntity` then add ECS components to SpatialOS-managed ECS entities, so if I want to add stuff like rendering/collision components, I have to do something like this:
```CSharp

    protected override void OnCreate()
    {
        newEntitiesQuery = GetEntityQuery(
            ComponentType.ReadOnly<SpatialEntityId>(),
            ComponentType.ReadOnly<Metadata.Component>(),
            ComponentType.ReadOnly<NewlyAddedSpatialOSEntity>());
        RequireForUpdate(newEntitiesQuery);
    }
    protected override void OnUpdate()
    {
        var toSync = newEntitiesQuery.ToEntityArray(Allocator.Temp);
        for (int i = 0; i < toSync.Length; i++)
        {
             // Adding all those components
        }
        toSync.Dispose();
    }
```

#### Why it's good
As you may know there are ways to copy entities, e.g. `EntityManager.Instantiate(Entity)` creates a new entity with same component set and data values in the world.

By providing custom authoring Monobehaviour, Unity enables users to design prefab in Editor, reference it, then use `GameObjectConversionUtility.ConvertGameObjectHierarchy()` to convert the whole GameObject hierachy to a new Entity. With the previously mentioned copying tool, we again can spawn editor time predefined objects in ECS world.

Now the only to-do to make this works in a SpatialOS project is, besides CreateEntity() in `EcsViewSystem.AddEntity()`, also accepts user-provided Entity as prefab.

As I can imagine, after this is done, local spawner systems are no longer needed. (Not sure if there are performance benefits in reducing all those AddComponentData() call)

#### Proposal
2 ways I can come up with are:
- As current `EcsViewSystem.AddEntity(EntityId)` takes an EntityId, allowing users to register a (EntityId, Entity) to a dictionary in the EcsViewSystem maybe the most compatible way. Users would have to do this before they send the CreateEntity world commands.
- A more sensible way would be to use _Metadata_ value as the prefab key. However it seems this is not possible without changing current systems design because Metadata is not created by EcsViewSystem.

**Comment by zeroZshadow** [comment]
There are currently plans to integrate with the conversion systems and provide this API, however it is currently not possible due to the required functionality being internal to the entities packages.

Due to the nature of SpatialOS networking there is no guarantee that we already have access to the Metadata component at the time we create the ECS entity.
If we want to "create" the entity once the `Metadata` has been checked out, we'd be too late as we now already have an ECS entity that is linked to the SpatialOS entity.

The solution is to spawn an entity with `GameObjectConversionUtility.ConvertGameObjectHierarchy()`, and somehow merge the new root entity with our already existing entity.
Sadly the functionality to copy all components from 1 entity to another, and remap any entity id's, is internal to the entities packages and cannot be accessed by us even through use of reflection.

We're looking for methods around this, but until then we won't have proper support for the conversion workflow.

**Comment by No3371** [comment]
Are you talking about GameObject -> Entity?
I understand you have your design concerns, just out of curiosity, if you don't mind 😉  I'd like to know what makes it impossible to use `EntityManager.Instantiate()` to clone an entity with desired ECS data then you add all your components on it, instead of `EntityManager.CreateEntity()` -> add your components -> users add desired components then set components data.

**Comment by zeroZshadow** [comment]
The issue is that, at the time of entity creation, you will have no information about what kind of entity is is. For example, you won't have the `Metadata` component. So how would you pick the prefab to convert into your new entity to add the Spatial OS components too?

**Comment by No3371** [comment]
I agree with you what prefab to use would be the problem, I was aware of this at time or raising this issue.

> #### Proposal
> ...
> - As current EcsViewSystem.AddEntity(EntityId) takes an EntityId, allowing users to register a (EntityId, Entity) to a dictionary in the EcsViewSystem maybe the most compatible way. Users would have to do this before they send the CreateEntity world commands.
>
> ...

Metadata is the natural choice for this case, I totally agree with that, at the same time I also feels your current design is pretty nice. That's why I mentioned the first idea: Since you are already offering ID reservations tools, It seems acceptable (just my opinion of course😁) to decide which Entity (ECS) to use in `EcsViewSystem.AddEntity()` by EntityID.

Changing current API is not needed, and the flow looks okay: reserving a EntityID -> Set (EntityID, Entity) to EcsViewSystem -> WorldCommands.CreateEntity.

What do you think? Not saying that you should do this, it's just me like to discuss with and learn from people working on big API.

**Comment by zeroZshadow** [comment]
In your example, only the worker that requests the entity spawn will know what prefab entity to use.
How do you propose other workers, such as clients, will create the ecs entity once they check out the newly created SpatialOS entity?

**Comment by No3371** [comment]
Solid point, I totally missed that! Not I see what you meant there's no way to achieve this (with current systems). Thanks! 😃
