### ISSUE TITLE
Feature Request: Support ISharedComponentData generation

### ISSUE THREAD

**Issue by No3371** [spatialos/gdk-for-unity#1398]
#### Description
Allowing configuration (Unity-side) of what component type a component schema to be generated in for more flexibility and performance potential in ECS systems.

With ISharedComponentData, entities will be stored to different chunks with a single component type, so we can operate on chunks, and no longer have to add additional tags to entities for querying purpose.

**Comment by zeroZshadow** [comment]
Could you explain a little bit more about the usecase behind this?

**Comment by No3371** [comment]
For example, I now have a component to be monster tier/type, it contains a value to indicate what it is.
This purpose is very simple so I don't want to use Metadata(string) for this, and entities with different values may have same Metadata, like: T1Fish is "Fish", T2Fish is also "Fish".

```
component Fish {
    id = n;
    int tier = 1;
}
```

If the component being generated to a **ISharedComponentData**, I can simply add the filter to the **EntityQuery** I made, then ECS gives me all the entities, it's efficient because entities are already put int different chunks based on the value.

But now I have to add additional ECS components like _FishT1_, _FishT2_, _FishT3_... or another custom **ISharedComponentData** _FishTier_ the entities when they are checked out for this purpose (more ECS components also means less entities could fit into a chunks)

Well, since we have limited resource available on GCP, every bit of performance is important, isn't it?

**Comment by zeroZshadow** [comment]
This is not a feature we'll currently be able to support.

However it should be trivial to implement yourself if you'd like.
You can add a system that runs just after the `SpatialOSReceiveGroup` and checks for entities with components you'd like to group on, and are missing the grouping component. Then you can add the shared component with the right value to group your entities. I'd recommend using an entity command buffer to keep things fast.

**Comment by No3371** [comment]
OK, thanks for replying 😄
