### ISSUE TITLE
Feature Request: Toggling managed worker in local launch

### ISSUE THREAD

**Issue by No3371** [spatialos/gdk-for-unity#1399]
#### Description
During development, to test/profile a managed worker, we sometimes need to manually run the worker outside of SpatialOS runtime. To stop a managed worker from being auto startup, we have to remove the worker completely from SpatialOS config file and **regenerate code** (What makes it worse: .json does not support commenting!)

It'd very handy to have a easy way to temporally toggle off a managed worker.

**Comment by jamiebrynes7** [comment]
Hey @No3371, sorry for the delayed response. 

From what you've described it seems as if the `manual_worker_connection_only` option in the load balancing config does what you are looking for? 

If this flag is set to true, it will signal the runtime not to start the workers itself and instead wait for you to start and connect them. 

You can find an example in https://github.com/spatialos/gdk-for-unity/blob/master/default_launch.json#L37

Toggling this shouldn't require you to regenerate code, but only restart the deployment.

**Comment by No3371** [comment]
OK, thanks for the info!
I've made a lot of issues 🤦 So I'm gonna just ask another question here: Is it possible to replace a managed worker with one running inside Unity Editor?

**Comment by jamiebrynes7** [comment]
> Is it possible to replace a managed worker with one running inside Unity Editor?

You can use the `spatial` CLI to 'replace' a worker running in the cloud - https://documentation.improbable.io/spatialos-tools/docs/cli-reference#section-spatial-project-deployment-worker-replace 😄

**Comment by No3371** [comment]
Thanks! I thought that command is starting a new process, didn't notice it's swapping 2 connected workers.
