### ISSUE TITLE
"Map Builder" function is undocumented.

### ISSUE THREAD

**Issue by StevenJNPearce** [spatialos/gdk-for-unity#1404]
#### Description
SpatialOS -> Map Builder is undocumented..

## Expected behaviour
Documentation should document all features

## Current behaviour
Documentation does not document all features

## Possible solution
Document it.

## Steps to reproduce
1. Open Editor with gdk-for-unity installed.
2. Look at the Map Builder with confusion, unsure if it has any relevance to your project..

**Comment by paulbalaji** [comment]
Hi @StevenJNPearce, the Map Builder is specific to the FPS project and is not a feature of the GDK for Unity.

Paul
