### ISSUE TITLE
Add string data to Player Lifecycle Creation

### ISSUE THREAD

**Issue by judah4** [spatialos/gdk-for-unity#590]
#### Description
There needs to be a way to send identifying data to the worker from the client. They way I've been able to get to work is to send string data through the create call and pass to the PlayerEntityTemplate Delegate.

## Possible solution
In `player_creator.schema`
```
type CreatePlayerRequestType
{
    improbable.Vector3f position = 1;
    string data = 2;
}
```

Delagate in `PlayerLifecycleConfig`
```CSharp
public delegate EntityTemplate GetPlayerEntityTemplateDelegate(
        string clientWorkerId,
        Vector3f position, string data);
```

This way when I want to create the player template, I can pass in this and process the data. In my case, split out the jwt and character id and load the data from my database.
```CSharp
PlayerLifecycleConfig.CreatePlayerEntityTemplate = (clientWorkerId, position, data) =>
{
    //do work
}
```

**Comment by jamiebrynes7** [comment]
Tracking the issue internally as UTY-1407

**Comment by judah4** [comment]
Oh, I do like that idea too. I was serializing my data to a string since I figured it was easy for people to get started that way. If youre able to serialize data as bytes with our own custom schema that would be even better!

Another solution I haven't tried yet would be providing a key, value data entry so people can pass a dictionary for custom data. I think I've seen photon do that for their PUN networking.

Something like
```
type CreatePlayerRequestType 
{
	improbable.Vector3f position = 1;
	map<int,string> metadata = 2;
}
```

Only reason I can see for not going the bytes route would be if it's more complex and not straight forward. Your example at least makes sense to me and I like it

**Comment by paulbalaji** [comment]
Hey @judah4, you can now do this on our `develop` branch as we've added the ability to pass arbitrary data with the player creation request. 

The `PlayerLifecycleHelper` class also contains `SerializeArguments` and `DeserializeArguments<T>` methods to help you serialize/deserialize what you want to send in the request.

We'll be adding better documentation on it before pushing it out with our next release :) 

PR: https://github.com/spatialos/gdk-for-unity/pull/809

**Comment by judah4** [comment]
Looking good 👍

**Comment by paulbalaji** [comment]
You can find this in our 0.2.0 release 🎉 

https://github.com/spatialos/gdk-for-unity/releases/tag/0.2.0
