### ISSUE TITLE
The postfix "Data" causes issues when generating code when the name is the same as the component

### ISSUE THREAD

**Issue by polartron** [spatialos/gdk-for-unity#609]
#### Description

A component with the name TestComponent using the type TestComponentData will give an error when generating code.

## Expected behaviour
It should generate code correctly.

## Current behaviour

../../schema\nobody\PlayerInputComponent.schema:38:2: Implicit autogenerated data type 'TestComponentData' for 'component TestComponent' (nobody.TestComponentData) conflicts with 'type TestComponentData' defined at ../../schema\nobody\PlayerInputComponent.schema:30:1.

## Steps to reproduce
Generate the following schema code.

type TestComponentData
{
	float some_data = 1;
}

component TestComponent
{
	id = 50000;
	TestComponentData test_data = 1;
}

## Environment
Unity 2018.2.10f1
Unity GDK 0.1.2

**Comment by jamiebrynes7** [comment]
Hey @polartron thanks for raising this! Tracking this internally as UTY-1433

**Comment by jamiebrynes7** [comment]
Hey @polartron after looking into this more closely, this error bubbles up from the `schema_compiler`. Under the hood this will take the fields inside each component and autogenerate a type called `ComponentNameData`. 

This is what you are hitting here where the auto-generated type has the same name as the component. In effect, the schema you've posted is illegal as it cannot resolve the difference between the two types. 

I'll try to get this documented publicly

**Comment by jamiebrynes7** [comment]
In the meantime, this particular feature of schemalang may actually fix your use case https://docs.improbable.io/reference/13.3/shared/schema/reference#reusable-data-types

(It looks like the example is a repro case, so I can't say for sure!)
