### ISSUE TITLE
Feature Request: Serializable structs from generated code

### ISSUE THREAD

**Issue by polartron** [spatialos/gdk-for-unity#677]
#### Description

I want to be able to define an entity template in a scriptableobject, making it easy for myself or designers to tweak values of components and creating new entity templates without touching any code.

## Expected behaviour

Adding the following code to a script or a scriptable object should make it editable in the inspector. The same should be possible for any component you generate.

`public Position.Snapshot positionComponent;`

![image](https://user-images.githubusercontent.com/38894848/50899274-e45fe480-1411-11e9-92c0-cfd73d88b7ea.png)

## Current behaviour
`public Position.Snapshot positionComponent;`

Does not display anything and can't be serialized.

## Possible solution
Adding [Serializable] to the component snapshot struct and all types that can be used and is serializable in a component.

![image](https://user-images.githubusercontent.com/38894848/50899295-f5a8f100-1411-11e9-9366-516fbbda0d1c.png)
![image](https://user-images.githubusercontent.com/38894848/50899306-fb063b80-1411-11e9-9120-c0b47823daa3.png)

**Comment by jamiebrynes7** [comment]
Tracking this internally as UTY-1705
