### ISSUE TITLE
Minor bug: ForwardingDispatcher accepts the CInterop LogLevel instead of UnityEngine.LogType

### ISSUE THREAD

**Issue by luna-duclos** [spatialos/gdk-for-unity#753]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).

-------

#### Description
A minor aesthethical issue mostly: The GDK's logging system normally does its best to abstract away CInterop stuff away from the end user. However, for the ForwardingDispatcher's constructor, it expects a CInterop.LogLevel as an argument

## Expected behaviour
I'd expect it to accept a UnityEngine.LogType instead, like the rest of the log API

## Current behaviour
It expects a CInterop.LogLevel instead, forcing me to reference that assembly.

## Possible solution
Change it and translate between the two via the already existing LogTypeMapping dict

## Steps to reproduce
N/A

## Environment
N/A

**Comment by jamiebrynes7** [comment]
Fixed in 0.2.4
