### ISSUE TITLE
Add back support for win x86

### ISSUE THREAD

**Issue by judah4** [spatialos/gdk-for-unity#780]
The SDK supported windows x86 builds but the current GDK does not without some modifications. To fix it the package com.improbable.gdk.tools needs some modifications.

In `.DownloadCoreSdk`, the program.cs imports needs this line added to pull the right sdk version for x86 machines.
```CSharp
new Package(tempPath, "worker_sdk", "core-dynamic-x86-win32", $"{nativeDependenciesPath}/Windows/x86", new List<string> {"include", "CoreSdkDll.lib"}),
```

Alongside that, `Plugins/PluginPostprocessor.cs` needs to be updated to not use the x86 dll in the editor and instead keep using the x86_64 one.
```CSharp
new PluginCompatibilitySetting(
                PluginType.Core,
                BuildTarget.StandaloneWindows,
                CpuType.X86,
                compatibleWithEditor: false
                ),
```

With this change the x86 windows client will not crash and work as intended! I'd do a pull request myself if allowed.

**Comment by jamiebrynes7** [comment]
The PR for this has been merged and will be released in `0.2.2`! 🎉
