### ISSUE TITLE
Subtractive component in query

### ISSUE THREAD

**Issue by jesta88** [spatialos/gdk-for-unity#781]
https://github.com/spatialos/gdk-for-unity/blob/7f10936647a58e33815cc2082bb4ba3ce0e7b921/workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/PlayerHeartbeatInitializationSystem.cs#L29

This seems weird to me, and Unity now throws an error for this:
EntityArchetypeQuery cannot contain Subtractive Component types

Why not simply specify the components inside GetComponentGroup? Query doesn't seem useful here.

**Comment by jamiebrynes7** [comment]
Thanks for flagging this up! 

This was fixed in https://github.com/spatialos/gdk-for-unity/pull/774 and will be released in 0.2.0.
