### ISSUE TITLE
Release v0.2.3

### ISSUE THREAD

**Issue by OriontheCat** [spatialos/gdk-for-unity#939]
Hi! I was just wondering what the ballpark is for the release is for 0.2.3 because Unity 2019.1 comes with ECS physics, and I don't want to rewrite all my physics logic.

**Comment by jessicafalk** [comment]
Hey @OriontheCat 
Could you elaborate what your question is? Are you currently using ECS physics?

**Comment by jamiebrynes7** [comment]
Hey @OriontheCat, `v0.2.3` was just released - https://github.com/spatialos/gdk-for-unity/releases/tag/0.2.3
