### ISSUE TITLE
Schema enums that don't start at 0 can have unexpected behaviour

### ISSUE THREAD

**Issue by jamiebrynes7** [spatialos/gdk-for-unity#960]
**Affects:** Release v0.1.0 and up.
**Internal Ticket:** [UTY-1970](https://improbableio.atlassian.net/browse/UTY-1970)

---

#### Description

If you have a schema enum like the following:

```
enum MyEnum {
	FOO = 1;
	BAR = 2;
}
```

the code generator generates code like the following:

```csharp
public enum MyEnum : uint {
	Foo = 1;
	Bar = 2;
}
```

This means that if this enum is used in a struct which is default constructed, the default value of that enum is invalid. For example:

```csharp
	public struct MyStruct 
	{
		public MyEnum Example;
	}

	public static void DoThing() 
	{
		var thing = new MyStruct();
		Debug.Log($"{thing.Example}"; // Prints "0"! This isn't a valid value for a type of "MyEnum"
	}
```

#### Workaround

Ensure that all schema enums start at `0`: 

```
enum MyEnum {
	FOO = 0;
	BAR = 1;
}
```

**Comment by BryanJY-Wong** [comment]
Fixed in v0.3.8. PR #1412
