### ISSUE TITLE
IL2CPP builds on Windows may fail

### ISSUE THREAD

**Issue by jessicafalk** [spatialos/gdk-for-unity#983]
**Affects:** Release v0.2.3 and up
**Internal Ticket:** [UTY-2049](https://improbableio.atlassian.net/browse/UTY-2049)

---

#### Description

IL2CPP builds on Windows might fail when building your worker for Windows. This happens when your project and Unity installation on the same drive and the path between those two is too long when il2cpp tries to resolve it.

#### Workaround

Either have your project in a different drive than your Unity installation or change the location of both the project and the Unity installation so that their paths become shorter.

**Comment by jamiebrynes7** [comment]
This issue was fixed in the 0.2.8 release
